// 195+ countries with dial codes, ISO codes and flags (emoji derived from ISO).
export type Country = { iso: string; name: string; ar: string; dial: string; len: number[] };

// len = list of valid national-number lengths (digits after the dial code)
export const COUNTRIES: Country[] = [
  { iso: 'AF', name: 'Afghanistan', ar: 'أفغانستان', dial: '93', len: [9] },
  { iso: 'AL', name: 'Albania', ar: 'ألبانيا', dial: '355', len: [9] },
  { iso: 'DZ', name: 'Algeria', ar: 'الجزائر', dial: '213', len: [9] },
  { iso: 'AD', name: 'Andorra', ar: 'أندورا', dial: '376', len: [6, 9] },
  { iso: 'AO', name: 'Angola', ar: 'أنغولا', dial: '244', len: [9] },
  { iso: 'AG', name: 'Antigua and Barbuda', ar: 'أنتيغوا وبربودا', dial: '1-268', len: [10] },
  { iso: 'AR', name: 'Argentina', ar: 'الأرجنتين', dial: '54', len: [10, 11] },
  { iso: 'AM', name: 'Armenia', ar: 'أرمينيا', dial: '374', len: [8] },
  { iso: 'AW', name: 'Aruba', ar: 'أروبا', dial: '297', len: [7] },
  { iso: 'AU', name: 'Australia', ar: 'أستراليا', dial: '61', len: [9] },
  { iso: 'AT', name: 'Austria', ar: 'النمسا', dial: '43', len: [10, 11] },
  { iso: 'AZ', name: 'Azerbaijan', ar: 'أذربيجان', dial: '994', len: [9] },
  { iso: 'BS', name: 'Bahamas', ar: 'الباهاما', dial: '1-242', len: [10] },
  { iso: 'BH', name: 'Bahrain', ar: 'البحرين', dial: '973', len: [8] },
  { iso: 'BD', name: 'Bangladesh', ar: 'بنغلاديش', dial: '880', len: [10] },
  { iso: 'BB', name: 'Barbados', ar: 'بربادوس', dial: '1-246', len: [10] },
  { iso: 'BY', name: 'Belarus', ar: 'بيلاروسيا', dial: '375', len: [9] },
  { iso: 'BE', name: 'Belgium', ar: 'بلجيكا', dial: '32', len: [9] },
  { iso: 'BZ', name: 'Belize', ar: 'بليز', dial: '501', len: [7] },
  { iso: 'BJ', name: 'Benin', ar: 'بنين', dial: '229', len: [8, 10] },
  { iso: 'BT', name: 'Bhutan', ar: 'بوتان', dial: '975', len: [8] },
  { iso: 'BO', name: 'Bolivia', ar: 'بوليفيا', dial: '591', len: [8] },
  { iso: 'BA', name: 'Bosnia and Herzegovina', ar: 'البوسنة والهرسك', dial: '387', len: [8] },
  { iso: 'BW', name: 'Botswana', ar: 'بوتسوانا', dial: '267', len: [8] },
  { iso: 'BR', name: 'Brazil', ar: 'البرازيل', dial: '55', len: [10, 11] },
  { iso: 'BN', name: 'Brunei', ar: 'بروناي', dial: '673', len: [7] },
  { iso: 'BG', name: 'Bulgaria', ar: 'بلغاريا', dial: '359', len: [9] },
  { iso: 'BF', name: 'Burkina Faso', ar: 'بوركينا فاسو', dial: '226', len: [8] },
  { iso: 'BI', name: 'Burundi', ar: 'بوروندي', dial: '257', len: [8] },
  { iso: 'KH', name: 'Cambodia', ar: 'كمبوديا', dial: '855', len: [8, 9] },
  { iso: 'CM', name: 'Cameroon', ar: 'الكاميرون', dial: '237', len: [9] },
  { iso: 'CA', name: 'Canada', ar: 'كندا', dial: '1', len: [10] },
  { iso: 'CV', name: 'Cape Verde', ar: 'الرأس الأخضر', dial: '238', len: [7] },
  { iso: 'CF', name: 'Central African Republic', ar: 'أفريقيا الوسطى', dial: '236', len: [8] },
  { iso: 'TD', name: 'Chad', ar: 'تشاد', dial: '235', len: [8] },
  { iso: 'CL', name: 'Chile', ar: 'تشيلي', dial: '56', len: [9] },
  { iso: 'CN', name: 'China', ar: 'الصين', dial: '86', len: [11] },
  { iso: 'CO', name: 'Colombia', ar: 'كولومبيا', dial: '57', len: [10] },
  { iso: 'KM', name: 'Comoros', ar: 'جزر القمر', dial: '269', len: [7] },
  { iso: 'CG', name: 'Congo', ar: 'الكونغو', dial: '242', len: [9] },
  { iso: 'CD', name: 'Congo (DRC)', ar: 'الكونغو الديمقراطية', dial: '243', len: [9] },
  { iso: 'CR', name: 'Costa Rica', ar: 'كوستاريكا', dial: '506', len: [8] },
  { iso: 'CI', name: "Côte d'Ivoire", ar: 'ساحل العاج', dial: '225', len: [8, 10] },
  { iso: 'HR', name: 'Croatia', ar: 'كرواتيا', dial: '385', len: [9] },
  { iso: 'CU', name: 'Cuba', ar: 'كوبا', dial: '53', len: [8] },
  { iso: 'CW', name: 'Curaçao', ar: 'كوراساو', dial: '599', len: [7, 8] },
  { iso: 'CY', name: 'Cyprus', ar: 'قبرص', dial: '357', len: [8] },
  { iso: 'CZ', name: 'Czechia', ar: 'التشيك', dial: '420', len: [9] },
  { iso: 'DK', name: 'Denmark', ar: 'الدنمارك', dial: '45', len: [8] },
  { iso: 'DJ', name: 'Djibouti', ar: 'جيبوتي', dial: '253', len: [8] },
  { iso: 'DM', name: 'Dominica', ar: 'دومينيكا', dial: '1-767', len: [10] },
  { iso: 'DO', name: 'Dominican Republic', ar: 'الدومينيكان', dial: '1-809', len: [10] },
  { iso: 'EC', name: 'Ecuador', ar: 'الإكوادور', dial: '593', len: [9] },
  { iso: 'EG', name: 'Egypt', ar: 'مصر', dial: '20', len: [10] },
  { iso: 'SV', name: 'El Salvador', ar: 'السلفادور', dial: '503', len: [8] },
  { iso: 'GQ', name: 'Equatorial Guinea', ar: 'غينيا الاستوائية', dial: '240', len: [9] },
  { iso: 'ER', name: 'Eritrea', ar: 'إريتريا', dial: '291', len: [7] },
  { iso: 'EE', name: 'Estonia', ar: 'إستونيا', dial: '372', len: [7, 8] },
  { iso: 'SZ', name: 'Eswatini', ar: 'إسواتيني', dial: '268', len: [8] },
  { iso: 'ET', name: 'Ethiopia', ar: 'إثيوبيا', dial: '251', len: [9] },
  { iso: 'FJ', name: 'Fiji', ar: 'فيجي', dial: '679', len: [7] },
  { iso: 'FI', name: 'Finland', ar: 'فنلندا', dial: '358', len: [9, 10] },
  { iso: 'FR', name: 'France', ar: 'فرنسا', dial: '33', len: [9] },
  { iso: 'GA', name: 'Gabon', ar: 'الغابون', dial: '241', len: [8, 9] },
  { iso: 'GM', name: 'Gambia', ar: 'غامبيا', dial: '220', len: [7] },
  { iso: 'GE', name: 'Georgia', ar: 'جورجيا', dial: '995', len: [9] },
  { iso: 'DE', name: 'Germany', ar: 'ألمانيا', dial: '49', len: [10, 11] },
  { iso: 'GH', name: 'Ghana', ar: 'غانا', dial: '233', len: [9] },
  { iso: 'GR', name: 'Greece', ar: 'اليونان', dial: '30', len: [10] },
  { iso: 'GD', name: 'Grenada', ar: 'غرينادا', dial: '1-473', len: [10] },
  { iso: 'GT', name: 'Guatemala', ar: 'غواتيمالا', dial: '502', len: [8] },
  { iso: 'GN', name: 'Guinea', ar: 'غينيا', dial: '224', len: [9] },
  { iso: 'GW', name: 'Guinea-Bissau', ar: 'غينيا بيساو', dial: '245', len: [9] },
  { iso: 'GY', name: 'Guyana', ar: 'غيانا', dial: '592', len: [7] },
  { iso: 'HT', name: 'Haiti', ar: 'هايتي', dial: '509', len: [8] },
  { iso: 'HN', name: 'Honduras', ar: 'هندوراس', dial: '504', len: [8] },
  { iso: 'HK', name: 'Hong Kong', ar: 'هونغ كونغ', dial: '852', len: [8] },
  { iso: 'HU', name: 'Hungary', ar: 'المجر', dial: '36', len: [9] },
  { iso: 'IS', name: 'Iceland', ar: 'آيسلندا', dial: '354', len: [7] },
  { iso: 'IN', name: 'India', ar: 'الهند', dial: '91', len: [10] },
  { iso: 'ID', name: 'Indonesia', ar: 'إندونيسيا', dial: '62', len: [9, 10, 11] },
  { iso: 'IR', name: 'Iran', ar: 'إيران', dial: '98', len: [10] },
  { iso: 'IQ', name: 'Iraq', ar: 'العراق', dial: '964', len: [10] },
  { iso: 'IE', name: 'Ireland', ar: 'أيرلندا', dial: '353', len: [9] },
  { iso: 'IL', name: 'Israel', ar: 'إسرائيل', dial: '972', len: [9] },
  { iso: 'IT', name: 'Italy', ar: 'إيطاليا', dial: '39', len: [9, 10] },
  { iso: 'JM', name: 'Jamaica', ar: 'جامايكا', dial: '1-876', len: [10] },
  { iso: 'JP', name: 'Japan', ar: 'اليابان', dial: '81', len: [10] },
  { iso: 'JO', name: 'Jordan', ar: 'الأردن', dial: '962', len: [9] },
  { iso: 'KZ', name: 'Kazakhstan', ar: 'كازاخستان', dial: '7', len: [10] },
  { iso: 'KE', name: 'Kenya', ar: 'كينيا', dial: '254', len: [9] },
  { iso: 'KI', name: 'Kiribati', ar: 'كيريباتي', dial: '686', len: [8] },
  { iso: 'KW', name: 'Kuwait', ar: 'الكويت', dial: '965', len: [8] },
  { iso: 'KG', name: 'Kyrgyzstan', ar: 'قيرغيزستان', dial: '996', len: [9] },
  { iso: 'LA', name: 'Laos', ar: 'لاوس', dial: '856', len: [9, 10] },
  { iso: 'LV', name: 'Latvia', ar: 'لاتفيا', dial: '371', len: [8] },
  { iso: 'LB', name: 'Lebanon', ar: 'لبنان', dial: '961', len: [7, 8] },
  { iso: 'LS', name: 'Lesotho', ar: 'ليسوتو', dial: '266', len: [8] },
  { iso: 'LR', name: 'Liberia', ar: 'ليبيريا', dial: '231', len: [7, 8] },
  { iso: 'LY', name: 'Libya', ar: 'ليبيا', dial: '218', len: [9] },
  { iso: 'LI', name: 'Liechtenstein', ar: 'ليختنشتاين', dial: '423', len: [7] },
  { iso: 'LT', name: 'Lithuania', ar: 'ليتوانيا', dial: '370', len: [8] },
  { iso: 'LU', name: 'Luxembourg', ar: 'لوكسمبورغ', dial: '352', len: [9] },
  { iso: 'MO', name: 'Macao', ar: 'ماكاو', dial: '853', len: [8] },
  { iso: 'MG', name: 'Madagascar', ar: 'مدغشقر', dial: '261', len: [9] },
  { iso: 'MW', name: 'Malawi', ar: 'مالاوي', dial: '265', len: [9] },
  { iso: 'MY', name: 'Malaysia', ar: 'ماليزيا', dial: '60', len: [9, 10] },
  { iso: 'MV', name: 'Maldives', ar: 'المالديف', dial: '960', len: [7] },
  { iso: 'ML', name: 'Mali', ar: 'مالي', dial: '223', len: [8] },
  { iso: 'MT', name: 'Malta', ar: 'مالطا', dial: '356', len: [8] },
  { iso: 'MH', name: 'Marshall Islands', ar: 'جزر مارشال', dial: '692', len: [7] },
  { iso: 'MR', name: 'Mauritania', ar: 'موريتانيا', dial: '222', len: [8] },
  { iso: 'MU', name: 'Mauritius', ar: 'موريشيوس', dial: '230', len: [8] },
  { iso: 'MX', name: 'Mexico', ar: 'المكسيك', dial: '52', len: [10] },
  { iso: 'FM', name: 'Micronesia', ar: 'ميكرونيزيا', dial: '691', len: [7] },
  { iso: 'MD', name: 'Moldova', ar: 'مولدوفا', dial: '373', len: [8] },
  { iso: 'MC', name: 'Monaco', ar: 'موناكو', dial: '377', len: [8, 9] },
  { iso: 'MN', name: 'Mongolia', ar: 'منغوليا', dial: '976', len: [8] },
  { iso: 'ME', name: 'Montenegro', ar: 'الجبل الأسود', dial: '382', len: [8] },
  { iso: 'MA', name: 'Morocco', ar: 'المغرب', dial: '212', len: [9] },
  { iso: 'MZ', name: 'Mozambique', ar: 'موزامبيق', dial: '258', len: [9] },
  { iso: 'MM', name: 'Myanmar', ar: 'ميانمار', dial: '95', len: [8, 9] },
  { iso: 'NA', name: 'Namibia', ar: 'ناميبيا', dial: '264', len: [9] },
  { iso: 'NR', name: 'Nauru', ar: 'ناورو', dial: '674', len: [7] },
  { iso: 'NP', name: 'Nepal', ar: 'نيبال', dial: '977', len: [10] },
  { iso: 'NL', name: 'Netherlands', ar: 'هولندا', dial: '31', len: [9] },
  { iso: 'NZ', name: 'New Zealand', ar: 'نيوزيلندا', dial: '64', len: [8, 9] },
  { iso: 'NI', name: 'Nicaragua', ar: 'نيكاراغوا', dial: '505', len: [8] },
  { iso: 'NE', name: 'Niger', ar: 'النيجر', dial: '227', len: [8] },
  { iso: 'NG', name: 'Nigeria', ar: 'نيجيريا', dial: '234', len: [10] },
  { iso: 'KP', name: 'North Korea', ar: 'كوريا الشمالية', dial: '850', len: [8, 10] },
  { iso: 'MK', name: 'North Macedonia', ar: 'مقدونيا الشمالية', dial: '389', len: [8] },
  { iso: 'NO', name: 'Norway', ar: 'النرويج', dial: '47', len: [8] },
  { iso: 'OM', name: 'Oman', ar: 'عمان', dial: '968', len: [8] },
  { iso: 'PK', name: 'Pakistan', ar: 'باكستان', dial: '92', len: [10] },
  { iso: 'PW', name: 'Palau', ar: 'بالاو', dial: '680', len: [7] },
  { iso: 'PS', name: 'Palestine', ar: 'فلسطين', dial: '970', len: [9] },
  { iso: 'PA', name: 'Panama', ar: 'بنما', dial: '507', len: [8] },
  { iso: 'PG', name: 'Papua New Guinea', ar: 'بابوا غينيا الجديدة', dial: '675', len: [8] },
  { iso: 'PY', name: 'Paraguay', ar: 'باراغواي', dial: '595', len: [9] },
  { iso: 'PE', name: 'Peru', ar: 'بيرو', dial: '51', len: [9] },
  { iso: 'PH', name: 'Philippines', ar: 'الفلبين', dial: '63', len: [10] },
  { iso: 'PL', name: 'Poland', ar: 'بولندا', dial: '48', len: [9] },
  { iso: 'PT', name: 'Portugal', ar: 'البرتغال', dial: '351', len: [9] },
  { iso: 'PR', name: 'Puerto Rico', ar: 'بورتوريكو', dial: '1-787', len: [10] },
  { iso: 'QA', name: 'Qatar', ar: 'قطر', dial: '974', len: [8] },
  { iso: 'RO', name: 'Romania', ar: 'رومانيا', dial: '40', len: [9] },
  { iso: 'RU', name: 'Russia', ar: 'روسيا', dial: '7', len: [10] },
  { iso: 'RW', name: 'Rwanda', ar: 'رواندا', dial: '250', len: [9] },
  { iso: 'KN', name: 'Saint Kitts and Nevis', ar: 'سانت كيتس ونيفيس', dial: '1-869', len: [10] },
  { iso: 'LC', name: 'Saint Lucia', ar: 'سانت لوسيا', dial: '1-758', len: [10] },
  { iso: 'VC', name: 'Saint Vincent', ar: 'سانت فينسنت', dial: '1-784', len: [10] },
  { iso: 'WS', name: 'Samoa', ar: 'ساموا', dial: '685', len: [7] },
  { iso: 'SM', name: 'San Marino', ar: 'سان مارينو', dial: '378', len: [6, 10] },
  { iso: 'ST', name: 'São Tomé and Príncipe', ar: 'ساو تومي وبرينسيبي', dial: '239', len: [7] },
  { iso: 'SA', name: 'Saudi Arabia', ar: 'المملكة العربية السعودية', dial: '966', len: [9] },
  { iso: 'SN', name: 'Senegal', ar: 'السنغال', dial: '221', len: [9] },
  { iso: 'RS', name: 'Serbia', ar: 'صربيا', dial: '381', len: [9] },
  { iso: 'SC', name: 'Seychelles', ar: 'سيشل', dial: '248', len: [7] },
  { iso: 'SL', name: 'Sierra Leone', ar: 'سيراليون', dial: '232', len: [8] },
  { iso: 'SG', name: 'Singapore', ar: 'سنغافورة', dial: '65', len: [8] },
  { iso: 'SK', name: 'Slovakia', ar: 'سلوفاكيا', dial: '421', len: [9] },
  { iso: 'SI', name: 'Slovenia', ar: 'سلوفينيا', dial: '386', len: [8] },
  { iso: 'SB', name: 'Solomon Islands', ar: 'جزر سليمان', dial: '677', len: [7] },
  { iso: 'SO', name: 'Somalia', ar: 'الصومال', dial: '252', len: [8, 9] },
  { iso: 'ZA', name: 'South Africa', ar: 'جنوب أفريقيا', dial: '27', len: [9] },
  { iso: 'KR', name: 'South Korea', ar: 'كوريا الجنوبية', dial: '82', len: [9, 10] },
  { iso: 'SS', name: 'South Sudan', ar: 'جنوب السودان', dial: '211', len: [9] },
  { iso: 'ES', name: 'Spain', ar: 'إسبانيا', dial: '34', len: [9] },
  { iso: 'LK', name: 'Sri Lanka', ar: 'سريلانكا', dial: '94', len: [9] },
  { iso: 'SD', name: 'Sudan', ar: 'السودان', dial: '249', len: [9] },
  { iso: 'SR', name: 'Suriname', ar: 'سورينام', dial: '597', len: [7] },
  { iso: 'SE', name: 'Sweden', ar: 'السويد', dial: '46', len: [9] },
  { iso: 'CH', name: 'Switzerland', ar: 'سويسرا', dial: '41', len: [9] },
  { iso: 'SY', name: 'Syria', ar: 'سوريا', dial: '963', len: [9] },
  { iso: 'TW', name: 'Taiwan', ar: 'تايوان', dial: '886', len: [9] },
  { iso: 'TJ', name: 'Tajikistan', ar: 'طاجيكستان', dial: '992', len: [9] },
  { iso: 'TZ', name: 'Tanzania', ar: 'تنزانيا', dial: '255', len: [9] },
  { iso: 'TH', name: 'Thailand', ar: 'تايلاند', dial: '66', len: [9] },
  { iso: 'TL', name: 'Timor-Leste', ar: 'تيمور الشرقية', dial: '670', len: [8] },
  { iso: 'TG', name: 'Togo', ar: 'توغو', dial: '228', len: [8] },
  { iso: 'TO', name: 'Tonga', ar: 'تونغا', dial: '676', len: [7] },
  { iso: 'TT', name: 'Trinidad and Tobago', ar: 'ترينيداد وتوباغو', dial: '1-868', len: [10] },
  { iso: 'TN', name: 'Tunisia', ar: 'تونس', dial: '216', len: [8] },
  { iso: 'TR', name: 'Türkiye', ar: 'تركيا', dial: '90', len: [10] },
  { iso: 'TM', name: 'Turkmenistan', ar: 'تركمانستان', dial: '993', len: [8] },
  { iso: 'TV', name: 'Tuvalu', ar: 'توفالو', dial: '688', len: [7] },
  { iso: 'UG', name: 'Uganda', ar: 'أوغندا', dial: '256', len: [9] },
  { iso: 'UA', name: 'Ukraine', ar: 'أوكرانيا', dial: '380', len: [9] },
  { iso: 'AE', name: 'United Arab Emirates', ar: 'الإمارات العربية المتحدة', dial: '971', len: [9] },
  { iso: 'GB', name: 'United Kingdom', ar: 'المملكة المتحدة', dial: '44', len: [10] },
  { iso: 'US', name: 'United States', ar: 'الولايات المتحدة', dial: '1', len: [10] },
  { iso: 'UY', name: 'Uruguay', ar: 'أوروغواي', dial: '598', len: [8] },
  { iso: 'UZ', name: 'Uzbekistan', ar: 'أوزبكستان', dial: '998', len: [9] },
  { iso: 'VU', name: 'Vanuatu', ar: 'فانواتو', dial: '678', len: [7] },
  { iso: 'VA', name: 'Vatican City', ar: 'الفاتيكان', dial: '39', len: [9, 10] },
  { iso: 'VE', name: 'Venezuela', ar: 'فنزويلا', dial: '58', len: [10] },
  { iso: 'VN', name: 'Vietnam', ar: 'فيتنام', dial: '84', len: [9, 10] },
  { iso: 'YE', name: 'Yemen', ar: 'اليمن', dial: '967', len: [9] },
  { iso: 'ZM', name: 'Zambia', ar: 'زامبيا', dial: '260', len: [9] },
  { iso: 'ZW', name: 'Zimbabwe', ar: 'زيمبابوي', dial: '263', len: [9] },
];

export function flagEmoji(iso: string): string {
  return iso
    .toUpperCase()
    .split('')
    .map((ch) => String.fromCodePoint(127397 + ch.charCodeAt(0)))
    .join('');
}
